echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "I am learning branching in git and github"
echo "Proud of you batch-33"
echo "Our new batch will start on 4th Oct"
echo "I am learning GIt first commands"
echo "I have installed git for windows on my laptop"
echo "I am very happy that i am able to install it "
