echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "Is this changes refected in git"
echo "This is 1st branch i am trying to mosify"
echo "In same line"
